# import = [
#     "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
# ]

# live_config_reload = true

[font]
size = 12

[font.bold]
family = "ComicShannsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "ComicShannsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "ComicShannsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "ComicShannsMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Return"
mods = "Control|Shift"

[terminal]
shell = "/bin/fish"

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 5

